# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME', 'Original Assets', '/vendor']
timezone: 'America/New_York'

# Miscellaneous
googleMapsAPIKey: "AIzaSyAvGdd7lRTgZrGDwURX87xxBuina1LL43k"

# Site Settings
title: "SwiftFest 2019"
email: "conference@swiftfest.io"
description: "The most community driven Swift conference!"
baseurl:
url: "swiftfest.io"
googleAnalyticsTrackingId: "UA-3309084-18"
googleAnalyticsSiteUrl: "swiftfest.io"
siteVerification: "-oXISG9WQeAZnsrs10KXZHl3DzLr_t9IOnmAmDTbMrI"

# Organizer Info
organizerName: "Giorgio Natili, Lucy Monahan, Barbara Menicucci, Alicia V Carr, Andres Pineda, "
organizerAlternateName: "SwiftFest Boston 2019"
organizerDescription: "Open and volunteer geek community who create exciting events and share experience about mobile development technology with passion. We do love Swift and everything mobile!"
organizerEmail: "conference@swiftfest.io"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://swiftfest.io"

# Head
metaKeywords: "event, swiftfest, boston, programming, swift, apple, ios, macos, tvos, watchos, developers, community, conference, learning, affordable, inclusion, diversity, scholarship"
twitterAccount: "@theSwiftFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://docs.google.com/forms/u/1/d/e/1FAIpQLSffougjfUt4bjecHeKWMgvhbiUBryAN-sU9irHQ-Ytdyih0Og/viewform"
c4sponsorsUrl: "mailto:conference@swiftfest.io"

# Navigation
navigationLinks:
# - {permalink: "/", text: "Home"}
# - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/code-of-conduct/", text: "Code of Conduct"}
 - {permalink: "/faq/", text: "FAQ"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/#tickets", text: "Tickets"}
 - {permalink: "/#partners", text: "Sponsors"}
 - {permalink: "https://2018.swiftfest.io", text: "2018"}
# - {permalink: "/team/", text: "Team"}
bottomNavigationLinks:
 - {link: "https://www.eventbrite.com/e/swiftfest-2019-tickets-56501408233#tickets", text: "Buy tickets"}
rightNavigationButtons:
 - {link: "https://www.eventbrite.com/e/swiftfest-2019-tickets-56501408233#tickets", text: "Buy tickets"}

# Hero Block
heroImage: "boston-sky.jpg"
heroTitle: "SwiftFest <typeout>  2019" # TODO: typeout?
eventDate: "July 29–30, 2019"
typeoutTextValues: '"", "Boston ", "Swift ", "Engineering ", "Community ", "Innovation ", "Open Source ", "Scripting ", "Development ", "Culture ", "Beantown ", "iOS ", "Excellence ", "Inclusiveness "'
typeoutFallback: "Boston"
heroButtons:
 - {permalink: "https://www.eventbrite.com/e/swiftfest-2019-tickets-56501408233#tickets", text: "Buy tickets", target: "_blank"}

# About Block
aboutTitle: "About SwiftFest"
aboutBlock:
 - {title: "Conference", image: "conference.png", text: "<p><strong>SwiftFest</strong> is a different way to experience <strong>iOS development</strong> that brings together engineers, architects, midnight coders, students, etc. in a highly social and vibrant environment entirely focused on <strong>Swift</strong>. The most community-driven Swift conference is happening for the second time in <strong>Boston</strong> – <strong>July 29-30</strong>, 2019.</p>" }
 - {title: "Workshops", image: "workshop.png", text: "At <b>SwiftFest</b> we'll be offering workshops along with talks and networking with some of the most innovative developers in the <b>Swift</b> space. Come along and elevate your <b>Swift</b> and <b>iOS</b> skills!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "300", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Swift"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from Boston and beyond"}
 - {count: "2", specialCharacter: "", info: "parallel tracks", detail: "catch the videos later!"} #TODO: tagline appropriate?

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Featured Speakers"
rockstarSpeakersButtonText: "See all the speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Calderwood Pavilion"
eventLocationLink: "https://www.huntingtontheatre.org/about/venue/pavilion/"
eventStreetAddress: "527 Tremont Street"
eventAddressLocality: "Boston"
eventAddressLocalityRegion: "MA"
eventPostalCode: "02116"
eventAddressCountry: "USA"
eventStartTime: "9:00 am"
eventDoorTime: "09:00"
eventEndTime: "6:00 pm"
eventPlaceCoordinates: "42.344797, -71.070950"
mapCenterCoordinates: "42.344848, -71.072060"
mapMobileCenterCoordinates: "42.344848, -71.072060"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Calderwood Pavilion"
venueFeatures: ["2 full theatrical stages", "Seating for 370", "Located in downtown Boston"]

# Tweets Feed Block
# TODO: need to set up tweetledee or delete this section https://github.com/tweetledee/tweetledee
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "swiftfest"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
partnersTitle: "Sponsors"
partnersC4sponsorsButton: "Become a sponsor for 2019!"

# Supporters Block
supportersTitle: "Supporters"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gnstudio.us6.list-manage.com/subscribe/post"
subscribeHiddenU: "66c929ea69a19ef75fd17625d"
subscribeHiddenId: "4ceb4a99c2"
subscribeInfo: "Find out about new speaker announcements and other SwiftFest news."

# Tickets Block
ticketsTitle: "Tickets"
ticketsInfo: "Conference ticket purchase includes 2 full days of sessions (July 29th–30th) and exhibitor booths, a ticket to the official conference party on July 29th, morning snack, lunch, and afternoon snack on both days."
ticketsOffers:
 -
   name: "Student"
   price: "99"
   priceCurrency: "USD"
   buyButtonLink: "https://www.eventbrite.com/e/swiftfest-2019-tickets-56501408233#tickets"
   buyButtonText: "Buy Now"
   additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund."
   validFrom: "2019-1-1T00:00"
   validThrough: "2019-07-28T9:00"
   soldOut: false
   disabled: false
   soldOutText: "Sold Out"
 -
  name: "At the Crack of Dawn"
  price: "199"
  priceCurrency: "USD"
  buyButtonLink: "https://www.eventbrite.com/e/swiftfest-2019-tickets-56501408233#tickets"
  buyButtonText: "Buy Now"
  additionalInfo: "Conference ticket purchase includes 2 full days of sessions (July 29th–30th) and exhibitor booths, a ticket to the official conference party on July 29th, morning snack, lunch, and afternoon snack on both days."
  validFrom: "2019-02-11T00:00"
  validThrough: "2019-04-08T23:59"
  soldOut: true
  disabled: false
  soldOutText: "Sold Out"
 -
  name: "Super Early Bird"
  price: "299"
  priceCurrency: "USD"
  buyButtonLink: "https://www.eventbrite.com/e/swiftfest-2019-tickets-56501408233#tickets"
  buyButtonText: "Buy Now"
  additionalInfo: "Conference ticket purchase includes 2 full days of sessions (July 29th–30th) and exhibitor booths, a ticket to the official conference party on July 29th, morning snack, lunch, and afternoon snack on both days."
  validFrom: "2019-02-11T00:00"
  validThrough: "2019-06-08T23:59"
  soldOut: true
  disabled: false
  soldOutText: "Sold Out"
 -
  name: "Early Bird"
  price: "399"
  priceCurrency: "USD"
  buyButtonLink: "https://www.eventbrite.com/e/swiftfest-2019-tickets-56501408233#tickets"
  buyButtonText: "Buy Now"
  additionalInfo: "Conference ticket purchase includes 2 full days of sessions (July 29th–30th) and exhibitor booths, a ticket to the official conference party on July 29th, morning snack, lunch, and afternoon snack on both days."
  validFrom: "2019-06-16T00:00"
  validThrough: "2019-07-08T23:59"
  soldOut: false
  disabled: false
  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=TheSwiftFest", icon: "twitter"}
 - {link: "https://www.facebook.com/theSwiftFest", icon: "facebook"}
 - {link: "https://www.linkedin.com/company/swiftfest/", icon: "linkedin"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Contacts"
  links:
   - {link: "mailto:conference@swiftfest.io", text: "conference@swiftfest.io"}
 -
  title: "FAQ"
  links:
   - {permalink: "/code-of-conduct/", text: "Code of Conduct"}
   - {permalink: "/diversity-inclusion/", text: "Diversity &amp; Inclusion"}
   - {permalink: "/logistics/", text: "Logistics"}


# Speakers List Block
showSessions: false

# Team Block
teamBlockTitle: "About us"
aboutUs: "SwiftFest is put on by a group of community builders in Boston passionate about Swift and mobile related technologies. We love bringing together engineers, architects, midnight coders, students, etc. in a highly social and vibrant environment to engage in technical discussions and to have fun."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "40.046741, -79.244695"
logisticsMapMobileCenterCoordinates: "42.412080, -71.733608"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "ship.jpg"
directionDetailsTitle: "Get around Boston"
directionDetailsCards:
 - {title: "From the Airport", information: 'Logan Airport is right next to the city. It is easily reachable by car, public transport, or taxi. More information is available at the <a href="http://www.massport.com/logan-airport/">airport website</a>.'}
 - {title: "Public Transit", information: 'You can take <a href="https://mbta.com">MBTA</a> buses and trains anywhere in Boston. You can take the Silver Line bus from the airport, but use Apple or Google Maps to find the best route for your time of day.'}
 - {title: "Hotels", information: 'Boston has a large range of hotels to choose from. We have some suggestions but you will have no problem finding a hotel to suit your preferences.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://www.marriott.com/hotels/hotel-photos/bosdm-courtyard-boston-downtown/", text: "Courtyard Boston Downtown (Official SwiftFest Hotel)"}
     - {link: "https://clubquartershotels.com/locations/club-quarters-hotel-boston", text: "Club Quarters Boston"}
     - {link: "http://www.wboston.com/", text: "W Boston"}
     - {link: "https://www.airbnb.com/s/Boston--MA", text: "AirBnb"}
   -
    title: "Registration"
    links:
     - {link: "https://www.eventbrite.com/e/swiftfest-2019-tickets-56501408233#tickets", text: "Buy Tickets"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://www.eventbrite.com/e/swiftfest-2019-tickets-56501408233", text: "Event Info"}
